# Tell Travis CI we're using PHP
language: php

# Using trusty instead of precise because we don't need PHP 5.2 or 5.3 anymore.
dist: trusty

addons:
  apt:
    packages:
      # Needed for `xmllint`.
      - libxml2-utils

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm/.cache
    - $HOME/phpunit-bin
    - $HOME/deployment-targets

branches:
  only:
    - master
    - develop

env: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true

install:
  - nvm install
  - composer install
  - export DEV_LIB_PATH=vendor/xwp/wp-dev-lib/scripts
  - source "$DEV_LIB_PATH/travis.install.sh"
  - npm run build:js

script:
  - source "$DEV_LIB_PATH/travis.script.sh"
  - if [ ! -z $JS_TESTS ]; then npm run test:js; fi

after_script:
  - source "$DEV_LIB_PATH/travis.after_script.sh"

jobs:
  fast_finish: true
  include:
    - stage: lint
      name: Lint
      php: "7.3"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpunit

    - stage: test
      name: JavaScript unit tests
      php: "7.3"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs,eslint,phpsyntax,phpunit JS_TESTS=1

    - name: PHP unit tests (7.3, WordPress latest)
      php: "7.3"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs,eslint,phpsyntax

    - name: PHP unit tests (7.2, WordPress latest)
      php: "7.2"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs,eslint

    - name: PHP unit tests (7.1, WordPress latest)
      php: "7.1"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs,eslint

    - name: PHP unit tests (7.0, WordPress latest)
      php: "7.0"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs,eslint

    - name: PHP unit tests (5.6, WordPress latest)
      php: "5.6"
      env: WP_VERSION=latest DEV_LIB_SKIP=phpcs,eslint

    - name: PHP unit tests (5.6, WordPress 5.1)
      php: "5.6"
      env: WP_VERSION=5.1    DEV_LIB_SKIP=phpcs,eslint,phpsyntax

    - name: PHP unit tests (5.5, WordPress 5.0)
      php: "5.5"
      env: WP_VERSION=5.0    DEV_LIB_SKIP=phpcs,eslint

    - name: PHP unit tests (5.4, WordPress 4.9)
      php: "5.4"
      env: WP_VERSION=4.9    DEV_LIB_SKIP=phpcs,eslint

    - stage: deploy
      if: type = push AND fork = false AND ( branch =~ ^[a-z][a-z0-9-]{0,10}$ OR branch =~ ^[0-9]+\.[0-9]+$ ) AND NOT branch IN ( live, test, dev, settings, team, support, debug, multidev, files, tags, billing )
      php: "7.1"
      env: WP_VERSION=latest DEV_LIB_ONLY=composer,grunt
      script:
        - |
          eval "$(ssh-agent -s)"
          pantheon_branch=$( echo $TRAVIS_BRANCH | sed 's/^\([0-9]\)/v\1/' | sed 's/[^a-z0-9-]/-/' )
          echo "Initializing deployment to Pantheon branch: $pantheon_branch"
          openssl aes-256-cbc -K $encrypted_7eb11f40d4e9_key -iv $encrypted_7eb11f40d4e9_iv -in bin/keys/id_rsa_ampconfdemo.enc -out bin/keys/id_rsa_ampconfdemo -d
          chmod 600 bin/keys/id_rsa_ampconfdemo
          ./bin/deploy-travis-pantheon.sh \
            ampconfdemo \
            db7f3307-9808-4753-aaa4-acb387c94472 \
            $(pwd)/bin/keys/id_rsa_ampconfdemo \
            $pantheon_branch
      after_script: skip
